stages:
  - test

.test: &test
  stage: test
  image: python:latest
  before_script:
    - python -m pip install --upgrade pip
    - if [ -f homework_09/requirements.txt ]; then pip install -r homework_09/requirements.txt; fi
  script:
    - cd homework_09/homework/
    - python manage.py test

M:test:
  <<: *test
  only:
    - master
    - homework_11

MR:test:
  <<: *test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
