name: Test for homework_10

on: [push]

jobs:
  homework_10:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f homework_09/requirements.txt ]; then pip install -r homework_09/requirements.txt; fi
    - name: Test Django
      run: |
        cd homework_09/homework/
        python manage.py test
